apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-statefulset
  namespace: stateful
spec:
  serviceName: mssql-service
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete # Retain
    whenScaled: Delete
  template:
    metadata:
      labels:
        app: mssql
    spec:
      terminationGracePeriodSeconds: 30
      hostname: mssqlinst
      securityContext:
        fsGroup: 10001
      containers:
      - name: mssql
        image: docker.io/abhinav2382/mssql:server-2022
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "@Aa123456789"
        - name: MSSQL_PID
          value: "Developer"
        volumeMounts:
        - name: data
          mountPath: /var/opt/mssql
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
      storageClassName: ontap-gold
