apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: stateful
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: houssemdocker/webapp:dotnet-v7.0.1.01
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 300m
            memory: "100Mi"
          requests:
            cpu: 100m
            memory: "50Mi"
        env:
        - name: ConnectionStrings__WebAppContext
          value: "Server=mssql-service;Database=ProdcutsDB;User ID=SA;Password=@Aa123456789;Encrypt=False;"
